server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb+srv://rutupawar999:rutu6march@cluster0.xfex8.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0


  application:
    name: journalApp